### ISSUE TITLE
randomize stats script

### ISSUE THREAD

**Issue by tborychowski** [petarku/swosUpdateHelper#8]
here's the algorithm

```js

const SUM = 20;
const RANGE = { from: 0, to: 7 };
const res = [7, 0, 0, 6, 0, 0, 0];


const rand = (min, max) => {
	return Math.floor(Math.random() * (max - min + 1) + min);
};


const remainder = () => SUM - res.reduce((p, c) => c += p, 0);

res.forEach((n, i) => {
	if (res[i]) return;
	const rem = remainder();
	const idx = i + 1;
	const remainingNumbers = res.length - i;

	let to = RANGE.to;
	let from = rem - (remainingNumbers - 1) * RANGE.to;
	if (from < 0) from = RANGE.from;
	if (rem < to) to = rem;

	res[i] = rand(from, to);
});

console.log(res, 20 - remainder());
```

**Comment by petarku** [comment]
well done ,  thanks @tborychowski  !

**Comment by petarku** [comment]
there is a bug in this code as we were speaking @tborychowski  
if i provide the following input 
const SUM = 33;
const RANGE = { from: 3, to: 7 };
const res = [0, 0, 0, 0, 0, 0, 0];
i would expect that in output res  i dont have any number smaller then 3  as 7*3 = 21 
however i get results as 
res= [ 4, 3, 7, 6, 7, 5, 1 ] which have 1 as a number that is not in provided range

no input validation is needed in script as i calling side will make sure that SUM is possible to be achieved with provided range. 
e.g it will not be possible to have input as SUM = 9 and range = {from: 3, to: 7}

**Comment by tborychowski** [comment]
Ha! A typo!
it should not be: 
```js
    if (from < 0) from = RANGE.from;
```
but: 
```js
    if (from < RANGE.from) from = RANGE.from;
```

**Comment by petarku** [comment]
thanks for this @tborychowski  , tested and it is working
